name: Main Test WL

on: push

workflow_dispatch:

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps: 
  
     - name: Checkout
       uses: actions/checkout@v2.4.0
  
     - name: Super-Linter
       uses: github/super-linter@v4.8.3
 
  
