name: Main Test WL

on: push

jobs:
  super-lint:
    name: Lint Code Base^
    runs-on: ubuntu-latest
    steps: 
  
     - name: Super-Linter
       uses: github/super-linter@v4.8.3
       
       env:
         DEFAULT_BRANCH: main
  
